### ISSUE TITLE
ZeroVoat 2.0 Update

### ISSUE THREAD

**Issue by dnelband** [zer0net/zerovoat#81]
test with two other clients, merger sites are added & zv.anonymous cert is generated on first visit to site if no zv.anonymous cert exists. pending issues:

- channel layout editor - under construction, will be ready in a day or two
- follow site / channel / topic
- comments are sometimes loading slow, will be optimized and solved

notes:
 - comments are now editable on the fly i.e if you are the user then you can edit it , thus i have removed the comments section because it seems redundant. do you agree?
 - i think notification for comments on topic / replies on comments / votes etc' will be an improvement, i read on several places that users would like to have it

the old version is backed up under this address - http://127.0.0.1:43110/1CcdBvpNiCoL85E3pcA9kYz83HhqrsMkFJ - for comparisons

**Comment by dnelband** [comment]
its live, i've signed & publish now again a couple of times

**Comment by antyhrabia** [comment]
I have problem after update. When I want to add a comment or file, it sends me to the main page (neither a comment nor a file is added). When I want to add a topic or channel, the button to be added does not react. Only thing I can do is to up vote or down vote topic or someone somment.

**Comment by dnelband** [comment]
hi @antyhrabia , thanks for the info, i've published a fix for ZeroVoat, please let me know its fixed for you

**Comment by antyhrabia** [comment]
Still the same (I can't comment, make topic or channel but this time it's not trasnferring me to the main site).

**Comment by dnelband** [comment]
hey @antyhrabia , did it work before and now it again didnt work, or did it not work all this time? i dont quite understand. can you please post screenshots of the error with a browser console view?
